### ISSUE TITLE
Export the Recorded Animation as video(mp4) file in gallery or any other application.

### ISSUE THREAD

**Issue by Shivam-Shrivastav** [hbock-42/widget_recorder#1]
Hi @hbock-42  I want to say that your this widget_record package is awesome.
I want to know that did you make it to export the recorded animation as video(mp4) file in phone's gallery or can we share that recorded animation as video in other application.
Please reply, I will be grateful if you reply.

Thank you.

**Comment by hbock-42** [comment]
Hello @starboy2102 and thank you. Currently we can only record an animation as APNG. To answer to the question if you can use it in your phone gallery, this is up to you, what I mean by that is, the animation is not saved locally, you have to do the work, I felt like this was not something related to this package, because some may want to send it somewhere from the application, some may want to save it locally, etc etc :)

**Comment by Shivam-Shrivastav** [comment]
Will you upgrade this package so as to export recorded animation  in the gallery as video or MP4 file in the future?

**Comment by hbock-42** [comment]
It is planned, but not in a near future, I am on holidays right now, but I would be pleased to merge your work if you have time to do it before me

**Comment by Shivam-Shrivastav** [comment]
Ok I will try to☺️

**Comment by hbock-42** [comment]
@starboy2102 Thank you, my first tough would be to check if there is an ffmpeg library for dart.
