### ISSUE TITLE
The recorded animation blinks continuously

### ISSUE THREAD

**Issue by tanvish99** [hbock-42/widget_recorder#2]
Hello, I was testing your example code and when the recording of the animation is completed, the recorded animation blinks at start and then it displays as expected. And while recording the animation slows down.

[Screenrecorder-2020-09-09-20-06-00-17.zip](https://github.com/hbock-42/widget_recorder/files/5195927/Screenrecorder-2020-09-09-20-06-00-17.zip)

**Comment by HugoB-sc** [comment]
@tanvish99 The recording is not blinking, it is the animations player witch is blinking, we can see it in your video when you wait a bit the player does not blink anymore. I invite you to save it locally then play it on your computer to check what I say :)

For the slowing part, this is expected behaviour, as I wait the recording of a frame is done to play then record the next one.

**Comment by hbock-42** [comment]
@tanvish99 The recording is not blinking, it is the animations player witch is blinking, we can see it in your video when you wait a bit the player does not blink anymore. I invite you to save it locally then play it on your computer to check what I say :)
For the slowing part, this is expected behaviour, as I wait the recording of a frame is done to play then record the next one.
